### ISSUE TITLE
datasets.builder.DatasetGenerationError: An error occurred while generating the dataset

### ISSUE THREAD

**Issue by PPPP-kaqiu** [JinYuanLi0012/PGIM#1]
When follow your instructions，dataset download raise an error[datasets.builder.DatasetGenerationError: An error occurred while generating the dataset]，it seems that when create the cache file in the cache but without downloading,so it's an empty file.

**Comment by JinYuanLi0012** [comment]
We haven't encountered this issue yet. Maybe you can try downloading the dataset from [here](https://www.modelscope.cn/datasets/Dexter1202/PGIM/files). In addition, we suspect that this may be related to the modelscope version. When we used modelscope versions 1.7.1 and 1.10.0, the problem did not occur.
