### ISSUE TITLE
twitter2017数据集错误

### ISSUE THREAD

**Issue by Ccccitrus** [JinYuanLi0012/PGIM#15]
您好 您twitter2017数据集压缩包中test.txt与valid.txt重复了。

从modelscope中查找到的数据集有相同的问题

是否可以麻烦您提供更新后的数据？

**Comment by JinYuanLi0012** [comment]
感谢指正，这是之前整理上传数据集时的一个疏忽，github仓库和modelscope平台的数据现均已更新为正确版本~
