### ISSUE TITLE
无法访问huggingface下载模型导致指令执行不成功

### ISSUE THREAD

**Issue by sore-2001** [JinYuanLi0012/PGIM#4]
我已经按照要求配置好所有环境，在最终执行时报错
(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /xlm-roberta-large/resolve/main/config.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f00c74d8880>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"),
我尝试把模型拷贝到本地，在yaml文件中修改模型位置，还是遇到上述问题。
希望您能帮帮我

**Comment by JinYuanLi0012** [comment]
该情况的出现是因为本地无法访问huggingface,和该仓库的代码和模型无关。需要在本地正确配置网络代理，解决国内无法直接访问huggingface问题。

**Comment by sore-2001** [comment]
请问如何在服务器上配置网络代理。我已更换三台服务器均未成功部署项目



---原始邮件---
发件人: "Jinyuan ***@***.***&gt;
发送时间: 2024年4月8日(周一) 下午5:59
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [JinYuanLi0012/PGIM] 无法访问huggingface下载模型导致指令执行不成功 (Issue #4)




 
该情况的出现是因为本地无法访问huggingface,和该仓库的代码和模型无关。需要在本地正确配置网络代理，解决国内无法直接访问huggingface问题。

**Comment by JinYuanLi0012** [comment]
export HF_ENDPOINT=https://hf-mirror.com
可以考虑尝试在运行本项目命令前，先运行该命令
