### ISSUE TITLE
manual annotation

### ISSUE THREAD

**Issue by hei789** [JinYuanLi0012/PGIM#8]
您好，不知道我对于论文的理解是否正确，如果正确我能不能拿到人工标注的数据集来学习一下？万分感谢
1. 人工标注少部分example
2. 利用训练好的vanilla MNER模型获得图文特征
3. 对于每一条训练数据，图文特征计算cos相似度，选取相似度最高的当做example
4. 组合Prompt送入大模型获取auxiliary Refined Knowledge

**Comment by JinYuanLi0012** [comment]
感谢关注，理解是正确的，人工实例已公开，请参见readme开头部分:)

**Comment by hei789** [comment]
十分感谢
